name: release workflow

on: 
 push:
   branches:
     - master
     - main
 workflow_dispatch:
permissions: write-all
  
jobs:
  release:
    name: Publish new release
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup node
        run: |
          echo "node_version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.node_version }}
      # - name: Configure committer
      #   run: |
      #     git config user.name "GitHub Actions Bot"
      #     git config user.email "<>"
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_TOEKN }}
          release-type: terraform-module
          package-name: standard-version
      # - name: git push release
      #   run: |
      #     git push --follow-tags origin master
